### ISSUE TITLE
"News" short intro description is missing

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-project.github.io#21]
In case we decided to delete the short intro for each piece of News, then skip this issue. Otherwise: Would it be possible to have this short intro as we had in the previous design?

**Comment by mathiasslawik** [comment]
Hey José,

with the refactoring, I changed the layout to make the teasers more explicit and consistent. They are now contained in the "teaser" attribute of the document and shown (if existing) on the news list. I've moved some of the teasers, but - as we discussed before - we should make them more pertinent and captivating to our target audiences so that people are enticed to read our news.

Best regards,
Mathias
